# configuration file for dotnet-releaser
[msbuild]
project = "./web/web.csproj"
configuration = "Release"
[github]
user = "Charon11"
repo = "test-dotnet"
[test]
enable = false
[coverage]
enable = false
[nuget]
publish = false
[brew]
publish = false
[scoop]
publish = false