name: Release new version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build
        run: dotnet build web -c Release
      - name: Publish
        run: dotnet publish web -c Release -o website
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: website/**
          if-no-files-found: error
      - name: Zip project # This would actually build your project, using zip for an example artifact
        run: |
          zip --junk-paths web-app website/**
      - run: curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin
        name: install autotag
      - name: bump version
        run: autotag
      - name: push version
        run: git push --tags
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
      - name: GH Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{steps.tag.outputs.tag}}
          tag_name: ${{steps.tag.outputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: web-app.zip
          asset_name: web-app.zip
          asset_content_type: application/zip
      